In [1]:
import cv2 as cv
import numpy as np

In [2]:
# Sets the image dimensions to 120 pixels high, 400 pixels wide, and 3 color channels (BGR). Defines the data type as an 8-bit unsigned integer (values from 0 to 255), which is the standard format for images
img = np.zeros((120, 400, 3), dtype=np.uint8)
cv.putText(img, "Hello, OpenCV!", (10, 80), cv.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 3)

cv.imshow("OpenCV OK", img)
cv.waitKey(0)
cv.destroyAllWindows()

cv.imwrite("./hello.png", img)

True

In [3]:
img = cv.imread("../images/roi.jpg")
img_grey = cv.imread("../images/roi.jpg", cv.IMREAD_GRAYSCALE)

cv.imshow("ROI", img)
cv.imshow("ROI (Grayscale)", img_grey)
cv.waitKey(0)
cv.destroyAllWindows()

In [4]:
img_resized = cv.resize(img, (400, 300))
img_shrinked = cv.resize(img, (0, 0), fx = 0.5, fy = 0.5)
img_scaled = cv.resize(img, (0, 0), fx = 2, fy = 2)

cv.imshow("ROI (Resized)", img_resized)
cv.imshow("ROI (Shrinked)", img_shrinked)
cv.imshow("ROI (Scaled)", img_scaled)
cv.waitKey(0)
cv.destroyAllWindows()

In [5]:
img_rotated = cv.rotate(img, cv.ROTATE_90_COUNTERCLOCKWISE)

cv.imshow("ROI (Rotated)", img_rotated)
cv.waitKey(0)
cv.destroyAllWindows()

In [6]:
print("Image shape:", img.shape)    # Height, Width, Channels

Image shape: (280, 450, 3)


In [ ]:
arr = np.array(
    [
        [[0, 0, 0], [255, 255, 255]],
        [[255, 255, 255], [0, 0, 0]]
    ], 
    dtype=np.uint8)

img = cv.resize(arr, (258, 258))
cv.imshow("Array Image", img)

img = cv.resize(arr, (200, 200), interpolation=cv.INTER_NEAREST)
cv.imshow("Array Image (Nearest Neighbor Interpolation)", img)

print(img[0, 0])  # Top-left pixel
print(img[199, 45:200]) # Bottom row, columns 45 to 199

img[0:100, 0:100] = [255, 0, 0]  # Top-left corner to blue
cv.imshow("Array Image (Red Corner)", img)

cv.waitKey(0)
cv.destroyAllWindows()

[0 0 0]
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [